# Generated by Django 6.1.1 on 2026-09-29 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms_builder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nazwa')),
                ('address', models.CharField(max_length=250, verbose_name='adres')),
                ('map_url', models.URLField(blank=True, verbose_name='link do mapy')),
                ('directions', models.TextField(blank=True, verbose_name='wskazówki dojazdu')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktywne')),
            ],
            options={
                'verbose_name': 'miejsce',
                'verbose_name_plural': 'miejsca',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='tytuł')),
                ('subtitle', models.CharField(blank=True, help_text='Np. „Warsztaty ikonopisania dla początkujących i zaawansowanych”.', max_length=250, verbose_name='podtytuł')),
                ('slug', models.SlugField(editable=False, max_length=220, unique=True, verbose_name='adres strony')),
                ('description', models.TextField(blank=True, help_text='Zwykły tekst. Pusta linia rozpoczyna nowy akapit, adresy stron stają się linkami.', verbose_name='opis')),
                ('leader', models.CharField(blank=True, max_length=200, verbose_name='prowadzący')),
                ('show_leader', models.BooleanField(default=True, verbose_name='pokazuj prowadzącego')),
                ('show_location', models.BooleanField(default=True, verbose_name='pokazuj miejsce')),
                ('program', models.TextField(blank=True, verbose_name='program')),
                ('show_program', models.BooleanField(default=False, verbose_name='pokazuj program')),
                ('what_to_bring', models.TextField(blank=True, verbose_name='co zabrać')),
                ('show_what_to_bring', models.BooleanField(default=False, verbose_name='pokazuj „co zabrać”')),
                ('accommodation', models.TextField(blank=True, verbose_name='noclegi i wyżywienie')),
                ('show_accommodation', models.BooleanField(default=False, verbose_name='pokazuj noclegi i wyżywienie')),
                ('notes', models.TextField(blank=True, help_text='Np. cena, numer konta, termin wpłaty, „deska płatna osobno”.', verbose_name='uwagi organizacyjne')),
                ('show_notes', models.BooleanField(default=True, verbose_name='pokazuj uwagi organizacyjne')),
                ('cover_image', models.ImageField(blank=True, upload_to='workshops/', verbose_name='zdjęcie')),
                ('show_cover_image', models.BooleanField(default=True, verbose_name='pokazuj zdjęcie')),
                ('publish_at', models.DateTimeField(blank=True, help_text='Od tej chwili warsztat jest widoczny na liście. Puste = szkic.', null=True, verbose_name='publikacja od')),
                ('registration_opens_at', models.DateTimeField(blank=True, help_text='Puste = od chwili publikacji.', null=True, verbose_name='zapisy od')),
                ('registration_closes_at', models.DateTimeField(blank=True, help_text='Puste = do rozpoczęcia pierwszego spotkania.', null=True, verbose_name='zapisy do')),
                ('registration_closed', models.BooleanField(default=False, help_text='Zamyka zapisy od razu, niezależnie od dat.', verbose_name='zapisy zamknięte ręcznie')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='odwołany')),
                ('cancellation_note', models.CharField(blank=True, max_length=250, verbose_name='informacja o odwołaniu')),
                ('is_archived', models.BooleanField(default=False, verbose_name='w archiwum')),
                ('phone_mode', models.CharField(choices=[('required', 'wymagane'), ('optional', 'opcjonalne'), ('hidden', 'ukryte')], default='required', max_length=10, verbose_name='telefon')),
                ('adult_confirmation_mode', models.CharField(choices=[('required', 'wymagane'), ('hidden', 'ukryte')], default='required', max_length=10, verbose_name='potwierdzenie pełnoletności')),
                ('remarks_mode', models.CharField(choices=[('optional', 'opcjonalne'), ('hidden', 'ukryte')], default='optional', max_length=10, verbose_name='uwagi do zgłoszenia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='zmieniono')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utworzył(a)')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workshops', to='workshops.location', verbose_name='miejsce')),
            ],
            options={
                'verbose_name': 'warsztat',
                'verbose_name_plural': 'warsztaty',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nazwa')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='opis')),
                ('capacity', models.PositiveSmallIntegerField(blank=True, help_text='Tylko wskazówka — zgłoszeń ponad limit system nie blokuje.', null=True, verbose_name='limit miejsc')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='cena (zł)')),
                ('price_note', models.CharField(blank=True, help_text='Np. „deska płatna osobno”.', max_length=150, verbose_name='uwaga do ceny')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='kolejność')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='workshops.workshop', verbose_name='warsztat')),
            ],
            options={
                'verbose_name': 'poziom',
                'verbose_name_plural': 'poziomy',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nazwa')),
                ('default_levels', models.TextField(blank=True, help_text='Jeden poziom w wierszu, np. „Początkujący”. Nowy warsztat tego rodzaju dostanie te poziomy na start.', verbose_name='domyślne poziomy')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='kolejność')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktywny')),
                ('default_form_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='forms_builder.formtemplate', verbose_name='domyślny szablon formularza')),
            ],
            options={
                'verbose_name': 'rodzaj warsztatów',
                'verbose_name_plural': 'rodzaje warsztatów',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='workshop',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workshops', to='workshops.workshoptype', verbose_name='rodzaj'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='data')),
                ('start_time', models.TimeField(verbose_name='od godziny')),
                ('end_time', models.TimeField(verbose_name='do godziny')),
                ('note', models.CharField(blank=True, max_length=150, verbose_name='uwaga')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='workshops.workshop', verbose_name='warsztat')),
            ],
            options={
                'verbose_name': 'spotkanie',
                'verbose_name_plural': 'spotkania',
                'ordering': ['date', 'start_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='session_ends_after_it_starts')],
            },
        ),
    ]
