# Generated by Django 6.1.1 on 2026-09-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='show_capacity_notice',
            field=models.BooleanField(default=True, help_text='Przy poziomie, na który jest już więcej zgłoszeń niż miejsc, formularz uprzedzi, że zgłoszenie może trafić na listę rezerwową.', verbose_name='informuj o przekroczonym limicie'),
        ),
    ]
