# Generated by Django 6.1.1 on 2026-09-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='nazwa')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='opis')),
            ],
            options={
                'verbose_name': 'szablon formularza',
                'verbose_name_plural': 'szablony formularzy',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=300, verbose_name='treść pytania')),
                ('help_text', models.CharField(blank=True, max_length=300, verbose_name='podpowiedź')),
                ('kind', models.CharField(choices=[('short_text', 'krótki tekst'), ('long_text', 'dłuższa odpowiedź'), ('yes_no', 'tak / nie'), ('single_choice', 'wybór jednej odpowiedzi'), ('multi_choice', 'wybór wielu odpowiedzi'), ('material', 'zamówienie materiału')], default='long_text', max_length=20, verbose_name='rodzaj odpowiedzi')),
                ('choices', models.TextField(blank=True, help_text='Jedna odpowiedź w wierszu (dla pytań z wyborem i zamówień materiałów).', verbose_name='możliwe odpowiedzi')),
                ('required', models.BooleanField(default=True, verbose_name='wymagane')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='kolejność')),
                ('is_active', models.BooleanField(default=True, help_text='Pytań, na które ktoś już odpowiedział, nie usuwamy — można je ukryć.', verbose_name='widoczne w formularzu')),
            ],
            options={
                'verbose_name': 'pytanie',
                'verbose_name_plural': 'pytania',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=300, verbose_name='treść pytania')),
                ('help_text', models.CharField(blank=True, max_length=300, verbose_name='podpowiedź')),
                ('kind', models.CharField(choices=[('short_text', 'krótki tekst'), ('long_text', 'dłuższa odpowiedź'), ('yes_no', 'tak / nie'), ('single_choice', 'wybór jednej odpowiedzi'), ('multi_choice', 'wybór wielu odpowiedzi'), ('material', 'zamówienie materiału')], default='long_text', max_length=20, verbose_name='rodzaj odpowiedzi')),
                ('choices', models.TextField(blank=True, help_text='Jedna odpowiedź w wierszu (dla pytań z wyborem i zamówień materiałów).', verbose_name='możliwe odpowiedzi')),
                ('required', models.BooleanField(default=True, verbose_name='wymagane')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='kolejność')),
                ('level_name', models.CharField(blank=True, help_text='Nazwa poziomu, np. „Początkujący”. Puste = pytanie dla wszystkich.', max_length=100, verbose_name='tylko dla poziomu')),
            ],
            options={
                'verbose_name': 'pytanie szablonu',
                'verbose_name_plural': 'pytania szablonu',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
    ]
