# Generated by Django 6.1.1 on 2026-09-29 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms_builder', '0001_initial'),
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.ForeignKey(blank=True, help_text='Puste = pytanie dla wszystkich poziomów.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='workshops.level', verbose_name='tylko dla poziomu'),
        ),
        migrations.AddField(
            model_name='question',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='workshops.workshop', verbose_name='warsztat'),
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='forms_builder.formtemplate', verbose_name='szablon'),
        ),
    ]
