# Generated by Django 6.1.1 on 2026-09-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(default='Chrześcijańskie Stowarzyszenie Twórców Sztuki Sakralnej „Ecclesia”', max_length=200, verbose_name='pełna nazwa organizatora')),
                ('org_short_name', models.CharField(default='Stowarzyszenie Ecclesia', help_text='W nagłówku strony i jako nazwa nadawcy e-maili, jeśli nie podano innej.', max_length=100, verbose_name='nazwa skrócona')),
                ('org_address', models.CharField(blank=True, max_length=250, verbose_name='adres')),
                ('contact_email', models.EmailField(blank=True, help_text='Pokazywany uczestnikom jako adres do kontaktu z organizatorem.', max_length=254, verbose_name='e-mail kontaktowy')),
                ('contact_phone', models.CharField(blank=True, max_length=32, verbose_name='telefon kontaktowy')),
                ('logo', models.ImageField(blank=True, help_text='Plik PNG lub JPG, najlepiej poziomy, do ok. 400 px szerokości.', upload_to='site/', verbose_name='logo')),
                ('bank_account_holder', models.CharField(blank=True, max_length=200, verbose_name='odbiorca przelewu')),
                ('bank_account_number', models.CharField(blank=True, help_text='Np. 12 3456 7890 1234 5678 9012 3456', max_length=40, verbose_name='numer konta')),
                ('privacy_policy_url', models.URLField(default='https://ecclesia.jezuici.pl/polityka-prywatnosci-cookies/', verbose_name='link do polityki prywatności')),
                ('privacy_text', models.TextField(default='Wyrażam zgodę na przetwarzanie i przechowywanie moich danych osobowych przez Chrześcijańskie Stowarzyszenie Twórców Sztuki Sakralnej „Ecclesia” w celu organizacji warsztatów. Dane są wyłącznie na użytek wewnętrzny organizatorów i nie są nikomu udostępniane. Mogę w każdej chwili zażądać wglądu w nie, ich poprawienia lub usunięcia.', verbose_name='zgoda na przetwarzanie danych (klauzula w formularzu)')),
                ('privacy_version', models.CharField(default='2026-10-v1', editable=False, max_length=20, verbose_name='wersja klauzuli')),
                ('marketing_text', models.CharField(default='Chcę otrzymywać e-mailem informacje o kolejnych warsztatach Stowarzyszenia.', max_length=300, verbose_name='zgoda na informacje o kolejnych warsztatach')),
                ('smtp_enabled', models.BooleanField(default=False, help_text='Wyłączone = poczta idzie przez serwer skonfigurowany przy instalacji.', verbose_name='wysyłaj przez poniższy serwer SMTP')),
                ('smtp_host', models.CharField(blank=True, max_length=200, verbose_name='serwer SMTP')),
                ('smtp_port', models.PositiveIntegerField(default=587, verbose_name='port')),
                ('smtp_security', models.CharField(choices=[('starttls', 'STARTTLS (zwykle port 587)'), ('ssl', 'SSL/TLS (zwykle port 465)'), ('none', 'brak (tylko serwer w sieci lokalnej)')], default='starttls', max_length=10, verbose_name='szyfrowanie')),
                ('smtp_username', models.CharField(blank=True, max_length=200, verbose_name='użytkownik')),
                ('smtp_password_encrypted', models.TextField(blank=True, editable=False, verbose_name='hasło (zaszyfrowane)')),
                ('from_name', models.CharField(blank=True, help_text='Np. „Warsztaty Ecclesia”.', max_length=100, verbose_name='nazwa nadawcy')),
                ('from_email', models.EmailField(blank=True, help_text='Musi być adresem, z którego serwer SMTP pozwala wysyłać (zwykle ten sam co użytkownik).', max_length=254, verbose_name='adres nadawcy')),
                ('reply_to', models.EmailField(blank=True, help_text='Gdy uczestnik kliknie „Odpowiedz”. Puste = adres nadawcy.', max_length=254, verbose_name='odpowiedzi kieruj na (Reply-To)')),
                ('admin_notifications', models.CharField(choices=[('immediate', 'od razu po każdym zgłoszeniu'), ('daily', 'raz dziennie — podsumowanie nowych zgłoszeń'), ('off', 'nie wysyłaj')], default='immediate', max_length=10, verbose_name='powiadomienia o nowych zgłoszeniach')),
                ('admin_notification_email', models.EmailField(blank=True, help_text='Puste = e-mail kontaktowy organizatora.', max_length=254, verbose_name='wysyłaj powiadomienia na adres')),
                ('last_digest_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='zmieniono')),
            ],
            options={
                'verbose_name': 'ustawienia',
                'verbose_name_plural': 'ustawienia',
            },
        ),
    ]
