# Generated by Django 6.1.1 on 2026-09-30 06:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='kiedy')),
                ('actor_email', models.CharField(blank=True, max_length=254, verbose_name='adres osoby')),
                ('action', models.CharField(max_length=120, verbose_name='co')),
                ('target', models.CharField(blank=True, max_length=250, verbose_name='czego dotyczy')),
                ('url', models.CharField(blank=True, max_length=250, verbose_name='adres w panelu')),
                ('details', models.TextField(blank=True, verbose_name='szczegóły')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kto')),
            ],
            options={
                'verbose_name': 'zdarzenie',
                'verbose_name_plural': 'dziennik zdarzeń',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
