# Generated by Django 6.1.1 on 2026-09-29 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms_builder', '0002_initial'),
        ('workshops', '0002_workshop_show_capacity_notice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='imię')),
                ('last_name', models.CharField(max_length=100, verbose_name='nazwisko')),
                ('email', models.EmailField(max_length=254, verbose_name='adres e-mail')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='telefon')),
                ('remarks', models.TextField(blank=True, verbose_name='uwagi do zgłoszenia')),
                ('adult_confirmed', models.BooleanField(default=False, verbose_name='potwierdzenie pełnoletności')),
                ('privacy_consent_at', models.DateTimeField(verbose_name='zgoda na przetwarzanie danych')),
                ('privacy_consent_version', models.CharField(max_length=20, verbose_name='wersja klauzuli')),
                ('marketing_consent', models.BooleanField(default=False, verbose_name='zgoda na informacje o warsztatach')),
                ('status', models.CharField(choices=[('new', 'nowe'), ('accepted', 'przyjęte'), ('waitlisted', 'lista rezerwowa'), ('rejected', 'odrzucone'), ('withdrawn', 'wycofane'), ('cancelled', 'anulowane')], db_index=True, default='new', max_length=12, verbose_name='status')),
                ('is_seen', models.BooleanField(default=False, verbose_name='przejrzane')),
                ('admin_notes', models.TextField(blank=True, verbose_name='notatki organizatora')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='data zgłoszenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='zmieniono')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='workshops.level', verbose_name='poziom')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='workshops.workshop', verbose_name='warsztat')),
            ],
            options={
                'verbose_name': 'zgłoszenie',
                'verbose_name_plural': 'zgłoszenia',
                'ordering': ['submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=300, verbose_name='treść pytania')),
                ('value', models.TextField(blank=True, verbose_name='odpowiedź')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='kolejność')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='forms_builder.question', verbose_name='pytanie')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='applications.application', verbose_name='zgłoszenie')),
            ],
            options={
                'verbose_name': 'odpowiedź',
                'verbose_name_plural': 'odpowiedzi',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adres e-mail')),
                ('first_name', models.CharField(max_length=100, verbose_name='imię')),
                ('last_name', models.CharField(max_length=100, verbose_name='nazwisko')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='telefon')),
                ('marketing_consent', models.BooleanField(default=False, verbose_name='zgoda na informacje o warsztatach')),
                ('marketing_consent_at', models.DateTimeField(blank=True, null=True, verbose_name='data zgody na informacje')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='zmieniono')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant', to=settings.AUTH_USER_MODEL, verbose_name='konto')),
            ],
            options={
                'verbose_name': 'uczestnik',
                'verbose_name_plural': 'uczestnicy',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='applications.participant', verbose_name='uczestnik'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['new', 'accepted', 'waitlisted'])), fields=('workshop', 'participant'), name='one_active_application_per_person'),
        ),
    ]
