# Generated by Django 6.1.1 on 2026-09-30 06:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='dodane przez'),
        ),
        migrations.AddField(
            model_name='application',
            name='source',
            field=models.CharField(choices=[('form', 'formularz na stronie'), ('panel', 'dodane w panelu')], default='form', max_length=8, verbose_name='źródło'),
        ),
        migrations.AddField(
            model_name='application',
            name='waitlist_position',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='miejsce na liście rezerwowej'),
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('new', 'nowe'), ('accepted', 'przyjęte'), ('waitlisted', 'lista rezerwowa'), ('rejected', 'odrzucone'), ('withdrawn', 'wycofane'), ('cancelled', 'anulowane')], max_length=12, verbose_name='poprzedni status')),
                ('new_status', models.CharField(choices=[('new', 'nowe'), ('accepted', 'przyjęte'), ('waitlisted', 'lista rezerwowa'), ('rejected', 'odrzucone'), ('withdrawn', 'wycofane'), ('cancelled', 'anulowane')], max_length=12, verbose_name='nowy status')),
                ('comment', models.TextField(blank=True, verbose_name='komentarz')),
                ('notified', models.BooleanField(default=False, verbose_name='wysłano powiadomienie')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='kiedy')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='applications.application', verbose_name='zgłoszenie')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kto')),
            ],
            options={
                'verbose_name': 'zmiana w zgłoszeniu',
                'verbose_name_plural': 'historia zgłoszeń',
                'ordering': ['changed_at', 'pk'],
            },
        ),
    ]
