# Generated by Django 6.1.1 on 2026-09-30 07:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def record_existing_consents(apps, schema_editor):
    """Applications sent before the consent register: their consents, as far as known."""
    Application = apps.get_model("applications", "Application")
    ConsentRecord = apps.get_model("applications", "ConsentRecord")
    records = []
    for application in Application.objects.all():
        channel = "panel" if application.source == "panel" else "form"
        common = {
            "participant_id": application.participant_id,
            "application_id": application.pk,
            "channel": channel,
            "created_at": application.privacy_consent_at,
        }
        records.append(
            ConsentRecord(kind="privacy", version=application.privacy_consent_version, **common)
        )
        if application.marketing_consent:
            records.append(ConsentRecord(kind="marketing", **common))
    ConsentRecord.objects.bulk_create(records)


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_review_and_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='anonymised_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='dane usunięto'),
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('privacy', 'przetwarzanie danych (klauzula w formularzu)'), ('marketing', 'informacje o kolejnych warsztatach')], max_length=10, verbose_name='zgoda')),
                ('given', models.BooleanField(default=True, verbose_name='udzielona')),
                ('text', models.TextField(blank=True, verbose_name='treść')),
                ('version', models.CharField(blank=True, max_length=20, verbose_name='wersja')),
                ('channel', models.CharField(choices=[('form', 'formularz zgłoszenia'), ('panel', 'zgłoszenie wpisane przez organizatora'), ('account', 'strona „Moje dane”'), ('link', 'link wypisu z e-maila')], max_length=10, verbose_name='sposób')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='kiedy')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='applications.application', verbose_name='zgłoszenie')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='applications.participant', verbose_name='uczestnik')),
            ],
            options={
                'verbose_name': 'zgoda',
                'verbose_name_plural': 'rejestr zgód',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.RunPython(record_existing_consents, migrations.RunPython.noop),
]
