# Generated by Django 6.1.1 on 2026-09-30 05:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('application_received', 'Potwierdzenie otrzymania zgłoszenia'), ('admin_new_application', 'Powiadomienie o nowym zgłoszeniu'), ('admin_daily_digest', 'Dzienne podsumowanie zgłoszeń')], max_length=40, unique=True, verbose_name='rodzaj')),
                ('subject', models.CharField(max_length=200, verbose_name='temat')),
                ('body', models.TextField(help_text='Zwykły tekst. Pusta linia rozpoczyna nowy akapit, adresy stron stają się linkami. Pola w nawiasach klamrowych zostaną zastąpione danymi.', verbose_name='treść')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='zmieniono')),
            ],
            options={
                'verbose_name': 'szablon e-maila',
                'verbose_name_plural': 'szablony e-maili',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254, verbose_name='odbiorca')),
                ('to_name', models.CharField(blank=True, max_length=200, verbose_name='nazwa odbiorcy')),
                ('subject', models.CharField(max_length=250, verbose_name='temat')),
                ('body_text', models.TextField(verbose_name='treść')),
                ('body_html', models.TextField(blank=True, verbose_name='treść HTML')),
                ('reply_to', models.EmailField(blank=True, max_length=254, verbose_name='Reply-To')),
                ('template_key', models.CharField(blank=True, choices=[('application_received', 'Potwierdzenie otrzymania zgłoszenia'), ('admin_new_application', 'Powiadomienie o nowym zgłoszeniu'), ('admin_daily_digest', 'Dzienne podsumowanie zgłoszeń')], max_length=40, verbose_name='szablon')),
                ('status', models.CharField(choices=[('queued', 'w kolejce'), ('sending', 'wysyłanie'), ('sent', 'wysłano'), ('failed', 'błąd')], db_index=True, default='queued', max_length=10, verbose_name='status')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='próby')),
                ('last_error', models.TextField(blank=True, verbose_name='ostatni błąd')),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='następna próba')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='utworzono')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='wysłano')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='applications.application', verbose_name='zgłoszenie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='nadawca w panelu')),
            ],
            options={
                'verbose_name': 'e-mail',
                'verbose_name_plural': 'e-maile',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
