# Generated by Django 6.1.1 on 2026-09-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_decision_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='template_key',
            field=models.CharField(blank=True, choices=[('application_received', 'Potwierdzenie otrzymania zgłoszenia'), ('admin_new_application', 'Powiadomienie o nowym zgłoszeniu'), ('admin_daily_digest', 'Dzienne podsumowanie zgłoszeń'), ('decision_accepted', 'Decyzja: przyjęcie'), ('decision_waitlisted', 'Decyzja: lista rezerwowa'), ('decision_rejected', 'Decyzja: odrzucenie'), ('decision_cancelled', 'Anulowanie udziału'), ('withdrawal_confirmed', 'Potwierdzenie rezygnacji'), ('admin_withdrawal', 'Powiadomienie o rezygnacji uczestnika')], max_length=40, verbose_name='szablon'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='key',
            field=models.CharField(choices=[('application_received', 'Potwierdzenie otrzymania zgłoszenia'), ('admin_new_application', 'Powiadomienie o nowym zgłoszeniu'), ('admin_daily_digest', 'Dzienne podsumowanie zgłoszeń'), ('decision_accepted', 'Decyzja: przyjęcie'), ('decision_waitlisted', 'Decyzja: lista rezerwowa'), ('decision_rejected', 'Decyzja: odrzucenie'), ('decision_cancelled', 'Anulowanie udziału'), ('withdrawal_confirmed', 'Potwierdzenie rezygnacji'), ('admin_withdrawal', 'Powiadomienie o rezygnacji uczestnika')], max_length=40, unique=True, verbose_name='rodzaj'),
        ),
    ]
