# Generated by Django 6.1.1 on 2026-09-30 07:28

import django.db.models.deletion
import workshop_manager.communications.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_review_and_history'),
        ('communications', '0003_withdrawal_template'),
        ('workshops', '0002_workshop_show_capacity_notice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('accepted', 'przyjęci'), ('waitlisted', 'lista rezerwowa'), ('active', 'wszyscy zgłoszeni (nowi, przyjęci i z listy rezerwowej)'), ('level', 'przyjęci na wybranym poziomie'), ('selected', 'zaznaczone osoby')], max_length=10, verbose_name='do kogo')),
                ('subject', models.CharField(max_length=200, verbose_name='temat')),
                ('body', models.TextField(help_text='Zwykły tekst. Pola w nawiasach klamrowych, np. {imie}, zostaną zastąpione danymi każdej osoby.', verbose_name='treść')),
                ('attachment', models.FileField(blank=True, help_text='Np. PDF z listą materiałów. Do 5 MB.', storage=workshop_manager.communications.models.private_storage, upload_to='attachments/%Y/', verbose_name='załącznik')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='utworzono')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='wysłano')),
                ('recipient_count', models.PositiveIntegerField(default=0, verbose_name='liczba odbiorców')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workshops.level', verbose_name='poziom')),
                ('selected', models.ManyToManyField(blank=True, to='applications.application', verbose_name='zaznaczone zgłoszenia')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='workshops.workshop', verbose_name='warsztat')),
            ],
            options={
                'verbose_name': 'wiadomość do uczestników',
                'verbose_name_plural': 'wiadomości do uczestników',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='broadcast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='communications.broadcast', verbose_name='wiadomość do uczestników'),
        ),
    ]
